name: csv-to-json.yaml
on:
  push:
    branches:
      - main
      - data

jobs:
  csv-to-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run CSV to JSON conversion
        run: python py/csvToJson.py

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate JSON files"
